# -*- coding: utf-8 -*-
"""constant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Lj2gKAVrRYu-VMV2yiuIqkQ6AMFn-fC
"""

OPENAI_API_KEY = 'REPLACE YOUR API KEY'
LANGSMITH_API_KEY = 'REPLACE YOUR API KEY'
HF_TOKEN = 'REPLACE YOUR HF_TOKEN'
